export const SETTING_REQUEST = 'SETTING_REQUEST';
export const SETTING_SUCCESS = 'SETTING_SUCCESS';
export const SETTING_FAIL = 'SETTING_FAIL';

export const UPDATE_SETTING_REQUEST = 'UPDATE_SETTING_REQUEST';
export const UPDATE_SETTING_SUCCESS = 'UPDATE_SETTING_SUCCESS';
export const UPDATE_SETTING_FAIL = 'UPDATE_SETTING_FAIL';

export const RESET_SETTING_REQUEST = 'RESET_SETTING_REQUEST';
export const RESET_SETTING_SUCCESS = 'RESET_SETTING_SUCCESS';
export const RESET_SETTING_FAIL = 'RESET_SETTING_FAIL';

export const EXIT_SETTING = "EXIT_SETTING";